# Generated by Django 3.2.5 on 2021-07-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qustion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
