# Generated by Django 3.2.5 on 2021-07-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qustion', '0002_texttesting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
    ]
