# Generated by Django 3.2.5 on 2021-07-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qustion', '0003_remove_question_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ranking', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('website', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='TextTesting',
        ),
    ]
